# Generated by Django 3.1.5 on 2021-01-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Fname', models.CharField(max_length=250)),
                ('Minit', models.CharField(max_length=250)),
                ('Lname', models.CharField(max_length=250)),
                ('Bdate', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
                ('Sex', models.CharField(max_length=250)),
                ('Salary', models.CharField(max_length=250)),
                ('ssn', models.AutoField(primary_key=True, serialize=False)),
                ('Super_ssn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('dno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
            options={
                'verbose_name_plural': "Emplyee's",
            },
        ),
    ]
