# Generated by Django 3.1.5 on 2021-01-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210110_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssn',
            options={'verbose_name_plural': 'SSN'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='Super_ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
