# Generated by Django 3.1.5 on 2021-01-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20210110_1521'),
        ('employee', '0003_auto_20210110_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Super_ssn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.dnumber'),
        ),
    ]
