# Generated by Django 3.1.5 on 2021-01-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pnumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnumber', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=250)),
                ('Plocation', models.CharField(max_length=250)),
                ('Dnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.dnumber')),
            ],
            options={
                'verbose_name_plural': 'Project Employee',
            },
        ),
    ]
