# Generated by Django 3.1.5 on 2021-01-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dlocation', models.CharField(max_length=250)),
                ('Dnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.dnumber')),
            ],
            options={
                'verbose_name_plural': 'Depts Locations',
            },
        ),
    ]
