# Generated by Django 3.1.5 on 2021-01-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentName',
            fields=[
                ('Sex', models.CharField(max_length=250)),
                ('Bdate', models.CharField(max_length=250)),
                ('Relationship', models.CharField(max_length=250)),
                ('Dependent_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Essn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Dependent Name',
            },
        ),
    ]
