# Generated by Django 3.1.5 on 2021-01-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dependent_name', models.CharField(max_length=250)),
                ('Sex', models.CharField(max_length=250)),
                ('Bdate', models.CharField(max_length=250)),
                ('Relationship', models.CharField(max_length=250)),
                ('Essn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.ssn')),
            ],
            options={
                'verbose_name_plural': 'Dependent Name',
            },
        ),
    ]
