# Generated by Django 3.1.5 on 2021-01-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=250)),
                ('Mgr_ssn', models.CharField(max_length=250)),
                ('Mgr_start_date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dnumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnumber', models.IntegerField(max_length=40)),
            ],
        ),
    ]
