# Generated by Django 3.1.5 on 2021-01-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210110_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Department'},
        ),
    ]
